### ISSUE TITLE
Strange Google Keep notes after using this repository

### ISSUE THREAD

**Issue by polmartisanahuja** [snowman4839/python-play-music-uploader#1]
Hi,

I've successfully installed and used this python-play-music-uploader, but after this, strange notes, that I've not created, have start to appear on my Google Keep account. They are mostly intelligible, some random characters, but they are starting to annoy me.

I guess that there is something related with this unofficial google music upload API and the fact that I've provided my google account password (as required). Somehow this API has hacked my Google account. 
I've tried to change the google password but the issue persist.

Is some one that has tried this repository suffering something similar? 

Thanks,

**Comment by snowman4839** [comment]
Sorry it took me so incredibly long to get back to you. I don’t use Google Keep so I wouldn’t know but I haven’t heard of anyone having problems with it. I would email Simon Weber (simon@simonmweber.com mailto:simon@simonmweber.com) as he is the maintainer of that API.

Thanks,
Josh
